name: "sync issue to projects beta"
on:
  issues:
    types: [opened]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Output result
        run: |
          echo '${{ github.event.node_id }}'
      - uses: actions/github-script@v5
        id: add-issue-to-projects-beta
        with:
          result-encoding: string
          github-token: ${{ secrets.SYNC_PROJECTS_BETA }}
          script: |
            const variables = {
              projectId: "PN_kwHOA3J0ac4AAvWk",
              issueId:  "I_kwDOG0h-vc5DXJVk"
            };
            const mutation = `
              mutation($projectId: ID!, $issueId: ID!) {
                addProjectNextItem(input: {projectId: $projectId, contentId: $issueId}) {
                  projectNextItem {
                    id
                  }
                }
              }
            `;
            const result = await github.graphql(mutation, variables);
            if (result && result.addProjectNextItem && result.addProjectNextItem.projectNextItem) {
              return result.addProjectNextItem.projectNextItem.id;
            }
            return '';
