name: "sync issue to projects beta"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: sunadoi/add-projects-beta
        with:
          github-token: ${{ secrets.SYNC_PROJECTS_BETA }}
          project-owner: "sunadoi"
          project-number: 1
          content-id: ${{ github.event.pull_request.node_id }}
