name: "sync issue to projects beta"
on:
  issues:
    types: [opened]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          result-encoding: string
          github-token: ${{ secrets.SYNC_PROJECTS_BETA }}
          script: |
            const projectId = "${{ github.event_name }}" === "pull_request" ? "PN_kwHOA3J0ac4AAvhN" : "PN_kwHOA3J0ac4AAvWk"
            console.log(projectId)
            const variables = {
              projectId: projectId,
              issueId:  "${{ github.event.issue.node_id }}"
            };
            const mutation = `
              mutation($projectId: ID!, $issueId: ID!) {
                addProjectNextItem(input: {projectId: $projectId, contentId: $issueId}) {
                  projectNextItem {
                    id
                  }
                }
              }
            `;
            const result = await github.graphql(mutation, variables);
            if (result && result.addProjectNextItem && result.addProjectNextItem.projectNextItem) {
              return result.addProjectNextItem.projectNextItem.id;
            }
            return '';
