name: "sync pr to projects beta"
on:
  pull_request:
    types: [opened]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          result-encoding: string
          github-token: ${{ secrets.SYNC_PROJECTS_BETA }}
          script: |
            const variables = {
              projectId: "PN_kwHOA3J0ac4AAvWk",
              issueId:  "${{ github.event.pull_request.node_id }}"
            };
            const mutation = `
              mutation($projectId: ID!, $issueId: ID!) {
                addProjectNextItem(input: {projectId: $projectId, contentId: $issueId}) {
                  projectNextItem {
                    id
                  }
                }
              }
            `;
            await github.graphql(mutation, variables);
